### ISSUE TITLE
Problem after updating passport to Passport 3.0

### ISSUE THREAD

**Issue by TheFive** [jaredhanson/passport-openstreetmap#1]
I had trouble in using OAuth with openstreetmap, so i tried to npm update my package to exclude any problems in my software. (it was an internal Error the openstreetmap server throwed)

Now i have this compbination:
   "passport": "^0.3.0",
    "passport-openstreetmap": "^0.1.2",

But after update to 3.0 i get an error in the function (taken from your example)

```
passport.use(new OpenStreetMapStrategy({
    consumerKey: config.getConfiguration().OPENSTREETMAP_CONSUMER_KEY,
    consumerSecret: config.getConfiguration().OPENSTREETMAP_CONSUMER_SECRET,
    callbackURL: config.getCallbackUrl()
  },
  function(token, tokenSecret, profile, done) {
    // asynchronous verification, for effect...
    process.nextTick(function () {

       // To keep the example simple, the user's OpenStreetMap profile is returned to
      // represent the logged-in user.  In a typical application, you would want
      // to associate the OpenStreetMap account with a user record in your database,
       // and return that user instead.
       return done(null, profile);
    });
  }
 ));
```

The Error is:
TypeError: Cannot set property 'user' of undefined
    at /Users/TheFive.osm/development/osmbc/node_modules/passport-openstreetmap/node_modules/passport-oauth/node_modules/passport/lib/passport/http/request.js:45:35
    at pass (/Users/TheFive.osm/development/osmbc/node_modules/passport/lib/authenticator.js:267:43)
    at serialized (/Users/TheFive.osm/development/osmbc/node_modules/passport/lib/authenticator.js:276:7)
    at /Users/TheFive.osm/development/osmbc/app.js:37:3
    at pass (/Users/TheFive.osm/development/osmbc/node_modules/passport/lib/authenticator.js:284:9)
    at Authenticator.serializeUser (/Users/TheFive.osm/development/osmbc/node_modules/passport/lib/authenticator.js:289:5)
    at IncomingMessage.req.login.req.logIn (/Users/TheFive.osm/development/osmbc/node_modules/passport-openstreetmap/node_modules/passport-oauth/node_modules/passport/lib/passport/http/request.js:43:29)
    at Strategy.strategy.success (/Users/TheFive.osm/development/osmbc/node_modules/passport/lib/middleware/authenticate.js:228:13)
    at verified (/Users/TheFive.osm/development/osmbc/node_modules/passport-openstreetmap/node_modules/passport-oauth/lib/passport-oauth/strategies/oauth.js:151:16)
    at /Users/TheFive.osm/development/osmbc/app.js:65:14

What do i have to change, to make it work with 3.0 ?

Thanks for your help.

Christoph

**Comment by analog-nico** [comment]
This is caused by introducing lazy session initialization in passport 0.3.0. See [the technical details](https://github.com/jaredhanson/passport/pull/399) and [Jared's explanation](https://github.com/jaredhanson/passport/issues/400#issuecomment-135162085).

All there needs to be done is to update passport-oauth to ^1.0.0.

**Comment by analog-nico** [comment]
FYI, passport@0.3.1 just got released which applies a general patch.
